package com.MDS.ThesisMDS.frontend.designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BulkLoadingDesign extends VerticalLayout {
    protected Button btnBulk1;
    protected Label lblBulk1;
    protected Button btnBulkInstant;
    protected Button btnBulk2;
    protected Label lblBulk2;
    protected Button btnBulkAnimate;
    protected Button btnBulk3;
    protected Label lblBulk3;
    protected Button btnCancel;

    public BulkLoadingDesign() {
        Design.read(this);
    }
}
