package com.MDS.ThesisMDS.frontend.designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TreeDetailDesign extends VerticalLayout {
    protected Label lblId;
    protected Label lblOperation;
    protected Label lblNode;
    protected Label lblDetail;
    protected Label lblNodeId;
    protected Label lblLocation;
    protected Label lblData;
    protected Label lblTreeId;
    protected Label lblTreeId2;
    protected Label lblTreeType;
    protected Label lblNodeCount;
    protected Label lblMaxLevel;
    protected Grid<com.MDS.ThesisMDS.backend.database.model.TreeNodeDB> grid;
    protected Button btnClose;

    public TreeDetailDesign() {
        Design.read(this);
    }
}
